/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import listeners.playlist.AddBtnActionListener;
import listeners.playlist.FindBtnActionListener;
import playlist.Mp3ListModel;

/**
 *
 * @author Антон
 */
public class GUI_mp3player extends javax.swing.JFrame {

    /**
     * Creates new form GUI_mp3player
     */
    public GUI_mp3player() {
        initComponents();
        secondInitComponents();
        createListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearch = new javax.swing.JPanel();
        tFieldFind = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnAddSong = new javax.swing.JButton();
        btnDeleteSong = new javax.swing.JButton();
        btnArrowUp = new javax.swing.JButton();
        btnArrowDown = new javax.swing.JButton();
        scrPanePlaylist = new javax.swing.JScrollPane();
        listPlaylist = new javax.swing.JList();
        sliderVolume = new javax.swing.JSlider();
        tgBtnMute = new javax.swing.JToggleButton();
        btnPrevousSong = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        btnNextSong = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuOpenPlaylist = new javax.swing.JMenuItem();
        menuSavePlaylist = new javax.swing.JMenuItem();
        separatorExit = new javax.swing.JPopupMenu.Separator();
        menuExit = new javax.swing.JMenuItem();
        menuService = new javax.swing.JMenu();
        menuChangeScin = new javax.swing.JMenu();
        menuScin1 = new javax.swing.JMenuItem();
        menuScin2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 300, 300));
        setResizable(false);

        panelSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tFieldFind.setFont(new java.awt.Font("Monospaced", 2, 14)); // NOI18N
        tFieldFind.setForeground(new java.awt.Color(204, 204, 204));
        tFieldFind.setToolTipText("");

        btnFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/search_16.png"))); // NOI18N
        btnFind.setText("Find");
        btnFind.setToolTipText("Find the song");

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tFieldFind)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFind)
                .addContainerGap())
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tFieldFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAddSong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/plus_16.png"))); // NOI18N
        btnAddSong.setToolTipText("Add song");

        btnDeleteSong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/remove_icon.png"))); // NOI18N
        btnDeleteSong.setToolTipText("Remove song");

        btnArrowUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/arrow-up-icon.png"))); // NOI18N
        btnArrowUp.setToolTipText("Arror song");

        btnArrowDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/arrow-down-icon.png"))); // NOI18N
        btnArrowDown.setToolTipText("Arror down");

        listPlaylist.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrPanePlaylist.setViewportView(listPlaylist);

        tgBtnMute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/speaker.png"))); // NOI18N
        tgBtnMute.setToolTipText("On/Off sound");
        tgBtnMute.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/mute.png"))); // NOI18N

        btnPrevousSong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/prev-icon.png"))); // NOI18N
        btnPrevousSong.setToolTipText("Previous track");

        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/Play.png"))); // NOI18N
        btnPlay.setToolTipText("Play selected track");

        btnPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/Pause-icon.png"))); // NOI18N
        btnPause.setToolTipText("Pause");

        btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/stop-red-icon.png"))); // NOI18N
        btnStop.setToolTipText("Stop playback");

        btnNextSong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/next-icon.png"))); // NOI18N
        btnNextSong.setToolTipText("Next treak");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrPanePlaylist)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddSong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteSong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnArrowDown)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnArrowUp))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tgBtnMute, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(sliderVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPrevousSong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPlay)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPause)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnStop)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNextSong)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnArrowDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnArrowUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteSong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddSong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(scrPanePlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sliderVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPrevousSong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPause, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNextSong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(tgBtnMute, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuFile.setText("File");

        menuOpenPlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/open-icon.png"))); // NOI18N
        menuOpenPlaylist.setText("Open playlist");
        menuFile.add(menuOpenPlaylist);

        menuSavePlaylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/save_16.png"))); // NOI18N
        menuSavePlaylist.setText("Save playlist ");
        menuFile.add(menuSavePlaylist);
        menuFile.add(separatorExit);

        menuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/exit.png"))); // NOI18N
        menuExit.setText("Exit");
        menuFile.add(menuExit);

        jMenuBar1.add(menuFile);

        menuService.setText("Edit");

        menuChangeScin.setText("Change Scin");

        menuScin1.setText("Web Look&feel");
        menuChangeScin.add(menuScin1);

        menuScin2.setText("Web Look&feel (black)");
        menuChangeScin.add(menuScin2);

        menuService.add(menuChangeScin);

        jMenuBar1.add(menuService);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void secondInitComponents(){
        mp3ListModel = new Mp3ListModel();
        listPlaylist.setModel(mp3ListModel);
    }
    
    private void createListeners(){
        AddBtnActionListener addBtnActLr = new 
                AddBtnActionListener(mp3ListModel);
        FindBtnActionListener findBtnActLr = new 
                FindBtnActionListener(tFieldFind, mp3ListModel);
        btnAddSong.addActionListener(addBtnActLr);
        btnFind.addActionListener(findBtnActLr);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_mp3player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_mp3player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_mp3player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_mp3player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GUI_mp3player().setVisible(true);
            }
        });
    }
    
    //Programmists declaration
    private Mp3ListModel mp3ListModel;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSong;
    private javax.swing.JButton btnArrowDown;
    private javax.swing.JButton btnArrowUp;
    private javax.swing.JButton btnDeleteSong;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnNextSong;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnPrevousSong;
    private javax.swing.JButton btnStop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JList listPlaylist;
    private javax.swing.JMenu menuChangeScin;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuOpenPlaylist;
    private javax.swing.JMenuItem menuSavePlaylist;
    private javax.swing.JMenuItem menuScin1;
    private javax.swing.JMenuItem menuScin2;
    private javax.swing.JMenu menuService;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JScrollPane scrPanePlaylist;
    private javax.swing.JPopupMenu.Separator separatorExit;
    private javax.swing.JSlider sliderVolume;
    private javax.swing.JTextField tFieldFind;
    private javax.swing.JToggleButton tgBtnMute;
    // End of variables declaration//GEN-END:variables
}